"""
Schemas for the Teaching Guide Ingestion Pipeline
"""

from typing import List, Optional
from pydantic import BaseModel


class TeachingGuideChunk(BaseModel):
    """Schema for teaching guide chunks stored in vector database"""
    id: Optional[str] = None  # Optional - will be auto-generated by database
    doc_id: str
    guide_type: str
    applicable_grades: List[str]
    topic: str
    subtopic: str
    section_header: str
    chunk_text: str
    page_start: int
    page_end: int
    is_general: bool
    applicable_categories: List[str] = []  # NEW: Learning categories this guide addresses
    lang: str = "fr"
