"""
Schemas for the Curriculum-Based Assessment Pipeline
"""

from typing import List, Optional
from pydantic import BaseModel


class CurriculumChunk(BaseModel):
    """Schema for curriculum chunks stored in vector database"""
    id: Optional[str] = None  # Optional - will be auto-generated by database
    cycle: str
    grades: List[str]
    subject: str
    section_type: str
    topic: str
    subtopic: str
    is_cycle_wide: bool
    chunk_text: str
    page_start: int
    page_end: int
    source_paragraph_id: str
    doc_id: str
    lang: str = "fr"


class AssessmentQuestion(BaseModel):
    """Schema for generated assessment questions"""
    id: str
    category: str
    difficulty_level: int
    question_type: str
    base_question: str
    options: List[dict]
    correct_answer: str
    explanation: str
    tags: List[str]
    curriculum_source: str  # Reference to curriculum chunk


class TeacherProfile(BaseModel):
    """Schema for teacher information used in retrieval"""
    teacher_id: str
    grade: str
    subject: str
    target_level: str = "intermediate"


class AssessmentRequest(BaseModel):
    """Schema for assessment generation requests"""
    teacher_id: str
    grade: str
    subject: str
    target_level: str = "intermediate"
    num_questions: int = 10


class AssessmentResponse(BaseModel):
    """Schema for assessment generation responses"""
    questions: List[AssessmentQuestion]
    metadata: dict
    curriculum_chunks_used: List[str]
